spring.application.name=springboot-tricol-api

# MySQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tricol_api
spring.datasource.username=postgres
spring.datasource.password=Badrino03
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.enabled=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Server Configuration
server.port=9005

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=86400000


